### ISSUE TITLE
Show tweets as embedded tweets

### ISSUE THREAD

**Issue by Mec-iS** [SpaceAppsXploration/xpreader-client#20]

**Comment by Mec-iS** [comment]
Same thing for the FB posts.

**Comment by pincopallino93** [comment]
Same thing for images and links?

**Comment by lyoshida** [comment]
Fb posts and tweets are now showing in the feed.

**Comment by Mec-iS** [comment]
Consider that 'media' type can be both images or videos.
By now is better to not display 'link' type.
