### ISSUE TITLE
UI Bug: Empty Article divs display only keywords

### ISSUE THREAD

**Issue by Mec-iS** [SpaceAppsXploration/xpreader-client#36]
![tweets_keywords_error](https://cloud.githubusercontent.com/assets/3146196/10559422/d7aaf838-74f0-11e5-9dcf-379d91964a2a.png)

**Comment by lyoshida** [comment]
Possible reason: Functions for embedding tweets and fb posts must load after the views are rendered.
To fix it, only embed tweets and fb posts after the calls are completed.

**Comment by lyoshida** [comment]
I fixed the issue using ajaxStop. We should look for a better way to handle this in the future.
