### ISSUE TITLE
Basic pagination

### ISSUE THREAD

**Issue by Mec-iS** [SpaceAppsXploration/xpreader-client#9]
Design a model and a ui component (just a link is ok for now) to paginate the articles.

The model has to hold the different tokens in the `bookmark` (`next`) property (see [API spec](https://github.com/SpaceAppsXploration/rdfendpoints/wiki/Articles-API))

**Comment by Mec-iS** [comment]
https://github.com/SpaceAppsXploration/xpreader-client/blob/master/static/scripts/models/models.js#L12

**Comment by lyoshida** [comment]
So the idea is just to have a "Load more articles" link the load the next batch of articles right? No pagination like "1 2 3 4 5 6 next>>"

**Comment by Mec-iS** [comment]
Taken some notes in the code: https://github.com/SpaceAppsXploration/xpreader-client/blob/master/static/scripts/models/models.js#L12
